/* ─────────────────────────────────────────────
   FFZG KOMPAS · shared data
   ───────────────────────────────────────────── */

window.KOMPAS_TIPS = [
  { id: 'iksica-popusti', cat: 'zivot',
    hr: { title: 'Iksica = popusti na kulturu i zabavu',
          body: 'S Iksicom možeš dobiti popust na kazališne ulaznice, muzeje, kina i mnoga druga mjesta u gradu. Uvijek pitaj na blagajni – iznenadit ćeš se koliko mjesta sudjeluje.',
          link: null },
    en: { title: 'Student card = discounts on culture and entertainment',
          body: 'Your student card gets you discounts at theatres, museums, cinemas and many other venues around the city. Always ask at the box office – you\'ll be surprised how many places participate.',
          link: null } },

  { id: 'vlak-besplatan', cat: 'novac',
    hr: { title: 'Besplatan vlak po cijeloj Hrvatskoj – od 2025.',
          body: 'Od 1. siječnja 2025. redovni studenti imaju pravo na potpuno besplatan prijevoz vlakom unutar RH. Potrebna je pametna kartica s HŽPP blagajne (uz potvrdu o studiranju s e-Građana). Izrada traje 7 dana, godišnja aktivacija košta 2,65 €.',
          link: 'https://www.hzpp.hr/hr/pametne-kartice-2/besplatna-putovanja-redovnih-studenata' },
    en: { title: 'Free train travel across Croatia – from 2025',
          body: 'From 1 January 2025, full-time students have the right to completely free train travel within Croatia. You need a smart card from an HŽPP ticket office (plus proof of enrolment from e-Građani). Card takes 7 days, annual activation costs €2.65.',
          link: 'https://www.hzpp.hr/hr/pametne-kartice-2/besplatna-putovanja-redovnih-studenata' } },

  { id: 'savjetovaliste', cat: 'pomoc',
    hr: { title: 'Besplatna psihološka podrška – povjerljivo',
          body: 'Savjetovalište FFZG-a radi od 1998. i nudi besplatnu psihološku pomoć svim studentima. Prijave mailom na savjet@ffzg.hr. Savjetovanje je 100% povjerljivo i moguće ga je dogovoriti online.',
          link: 'https://savjetovaliste.ffzg.unizg.hr/' },
    en: { title: 'Free psychological support – confidential',
          body: 'The FFZG counselling service has been running since 1998 and offers free psychological help to all students. Book by email at savjet@ffzg.hr. Fully confidential, online sessions available.',
          link: 'https://savjetovaliste.ffzg.unizg.hr/' } },

  { id: 'cetiri-pokusaja', cat: 'studij',
    hr: { title: 'Imaš 4 pokušaja za položiti ispit',
          body: 'Svaki kolegij možeš polagati 4 puta. Ako ne položiš ni u četvrtom roku, moraš upisati predmet iznova. Ne ostavljaj sve za kraj – što prije položiš, manje stresa.',
          link: null },
    en: { title: 'You have 4 attempts to pass each exam',
          body: 'Every course can be sat 4 times. Fail all four and you have to re-enrol the subject. Don\'t leave it to the end – the sooner you pass, the less stress.' } },

  { id: 'zet-popust', cat: 'novac',
    hr: { title: 'Iksica = studentski popust na ZET',
          body: 'Mjesečni ZET pokaz kupuješ uz studentski popust s Iksicom. Provjeri aktualne cijene na ZET-ovim prodajnim mjestima.',
          link: 'https://www.zet.hr' },
    en: { title: 'Student card = discounted ZET pass',
          body: 'Buy a monthly ZET zone pass at a student discount with your student card. Check current prices at ZET sales points.',
          link: 'https://www.zet.hr' } },

  { id: 'wc', cat: 'zivot',
    hr: { title: 'Gdje su WC-i',
          body: 'U glavnoj zgradi na svakom katu, blizu stubišta. U knjižnici uz stubište, podrum, 2. i 4. kat.',
          link: null },
    en: { title: 'Where are the toilets',
          body: 'Main building, every floor, near the stairs. Library, by the stairs, basement, 2nd and 4th floor.',
          link: null } },

  { id: 'knjiznica-generalno', cat: 'zivot',
    hr: { title: 'Knjižnica FFZG-a – što sve možeš koristiti',
          body: 'Besplatna za studente: posudba knjiga s iksicom, čitaonice za učenje, računala s AAI prijavom, tisak i skeniranje po niskim cijenama. Pristup digitalnim bazama podataka za humanistiku i društvene znanosti. Radi i subotom.',
          link: 'https://knjiznica.ffzg.unizg.hr/' },
    en: { title: 'FFZG Library – what you can actually use',
          body: 'Free for students: borrow books with your student card, use reading rooms and computers (AAI login), print and scan cheaply. Digital humanities and social science databases included. Open Saturdays too.',
          link: 'https://knjiznica.ffzg.unizg.hr/' } },

  { id: 'knjiznica-posudba', cat: 'sustavi',
    hr: { title: 'Knjižnica posuđuje na 14 dana',
          body: 'Knjige posuđuješ s iksicom – možeš produžiti do 2 puta, telefonom, mailom ili online s AAI računom.',
          link: 'https://knjiznica.ffzg.unizg.hr/usluge/posudba/' },
    en: { title: 'Library loans run 14 days',
          body: 'Borrow books with your library card – renew up to 2 times by phone, email or online with your AAI account.',
          link: 'https://knjiznica.ffzg.unizg.hr/usluge/posudba/' } },

  { id: 'menza-menu', cat: 'zivot',
    hr: { title: 'Provjeri menu menze online svaki dan',
          body: 'Dnevni menu menze FFZG-a objavljuje se svaki dan na webu SC-a – znaš što te čeka prije nego što siđeš u podrum.',
          link: 'https://www.sczg.unizg.hr/prehrana/restorani/filozofski-fakultet' },
    en: { title: 'Check the canteen menu online every day',
          body: 'The FFZG canteen\'s daily menu is posted every day on the SC website – know what\'s on before heading to the basement.',
          link: 'https://www.sczg.unizg.hr/prehrana/restorani/filozofski-fakultet' } },

  { id: 'studomat-upis', cat: 'sustavi',
    hr: { title: 'Predmet upisuješ preko Studomata',
          body: 'Kolegije upisuješ na Studomatu u zadanim rokovima. Datume objavljuje odsjek – prati ih od prvog tjedna. Propustiš li rok, javi se referadi.',
          link: 'https://www.isvu.hr/studomat' },
    en: { title: 'Enrol courses via Studomat',
          body: 'Enrol in courses on Studomat within the set windows. Your department posts the dates – check from week one. Missed it? Contact the referada.',
          link: 'https://www.isvu.hr/studomat' } },

  { id: 'pravobranitelj', cat: 'pomoc',
    hr: { title: 'Studentski pravobranitelj – tvoja zaštita',
          body: 'Ozbiljan konflikt s profesorom ili kršenje pravilnika? Studentski pravobranitelj prima pritužbe diskretno i besplatno te brani tvoja prava pred upravom. Kontaktiraj ga preko Studentskog zbora.',
          link: 'https://szbor.ffzg.unizg.hr/' },
    en: { title: 'Student ombudsman – your protection',
          body: 'Serious conflict with a professor or a rule violation? The student ombudsman accepts complaints discreetly and for free, defending your rights before the administration. Contact via the Student Council.',
          link: 'https://szbor.ffzg.unizg.hr/' } },

  { id: 'drzavna-stipendija', cat: 'novac',
    hr: { title: 'Državna stipendija – prati natječaj MZOM-a',
          body: 'Ministarstvo znanosti raspisuje natječaj jednom godišnje, obično krajem listopada ili početkom studenog. Prijava je online preko sustava Vidra s e-Građanima. Prati stranice MZOM-a za točan rok.',
          link: 'https://mzom.gov.hr' },
    en: { title: 'State scholarship – watch for the MZOM call',
          body: 'The Ministry of Science opens applications once a year, usually late October or early November. Apply online via the Vidra system using e-Građani. Follow the MZOM website for the exact deadline.',
          link: 'https://mzom.gov.hr' } },

  { id: 'bicikl-bajs', cat: 'zivot',
    hr: { title: 'Biciklom do faksa – stalci i Bajs u blizini',
          body: 'Stalci za bicikle nalaze se sa strane zgrade, lijevo od ulaza. U blizini su i dvije Bajs stanice – jedna kod ulaza, jedna s druge strane ceste.',
          link: null },
    en: { title: 'Cycling to campus – racks and Bajs nearby',
          body: 'Bike racks are on the side of the building, left of the entrance. There are also two Bajs public bike stations – one near the entrance, one across the road.',
          link: null } },

  { id: 'knjiznica-racunala', cat: 'sustavi',
    hr: { title: 'Javna računala u Knjižnici – treba AAI',
          body: 'Na prvom katu Knjižnice ima javno dostupnih računala s printerom i skenerom. Za prijavu trebaš AAI@EduHr račun. Radi tijekom radnog vremena knjižnice.',
          link: 'https://knjiznica.ffzg.unizg.hr/' },
    en: { title: 'Public PCs in the Library – AAI required',
          body: 'The Library\'s first floor has publicly available computers with a printer and scanner. Log in with your AAI@EduHr account. Open during library hours.',
          link: 'https://knjiznica.ffzg.unizg.hr/' } },


  { id: 'rok-odjave', cat: 'studij',
    hr: { title: 'Rok za odjavu kolegija ≠ rok ispita',
          body: 'Kolegij odjavljuješ na Studomatu unutar 2 tjedna od početka semestra. Kasnije = ostaješ upisan.',
          link: null },
    en: { title: 'Course drop deadline ≠ exam deadline',
          body: 'Drop a course on Studomat within 2 weeks of semester start. Later = stuck with it.',
          link: null } },

  { id: 'ispitni-rokovi', cat: 'studij',
    hr: { title: 'Ispitne rokove možeš naći na stranicama odsjeka',
          body: 'Svaki odsjek objavljuje raspored ispitnih rokova na svojoj web stranici. Provjeri na početku semestra i upiši rokove u kalendar – ne čekaj da ti netko javi.',
          link: null },
    en: { title: 'Exam dates are on your department\'s website',
          body: 'Every department publishes its exam schedule on its own web page. Check at the start of semester and put the dates in your calendar – don\'t wait to be told.',
          link: null } },


  { id: 'strani-jezici', cat: 'pomoc',
    hr: { title: 'Centar za strane jezike – popust za studente',
          body: 'Tečajevi engleskog, njemačkog, francuskog itd. – uz Iksicu znatno jeftinije.',
          link: 'https://centarzastranejezike.ffzg.unizg.hr' },
    en: { title: 'Foreign language centre – student rates',
          body: 'English, German, French etc. – significantly cheaper with student card.' } },

  { id: 'ksff', cat: 'zivot',
    hr: { title: 'KSFF – kultno studentsko okupljalište',
          body: 'Klub studenata u podrumu fakulteta. Kultno mjesto za kavu, kvizove i brucošijade – jedan od najaktivnijih studentskih klubova u gradu.',
          link: 'https://web.facebook.com/kaesefef/?locale=hr_HR' },
    en: { title: 'KSFF – the cult student hangout',
          body: 'Student club in the faculty basement. The go-to spot for coffee, quizzes and freshman events – one of the most active student clubs in the city.',
          link: 'https://web.facebook.com/kaesefef/?locale=hr_HR' } },

  { id: 'knjiznica-velicina', cat: 'zivot',
    hr: { title: 'Druga najveća knjižnica u Hrvatskoj',
          body: 'Knjižnica FFZG-a odmah je iza NSK-a – preko 600.000 svezaka, 750 radnih mjesta i 200+ računala raspoređenih na 7 etaža (prizemlje, 5 katova, podrum).',
          link: 'https://knjiznica.ffzg.unizg.hr/' },
    en: { title: 'Second largest library in Croatia',
          body: 'The FFZG library is right behind the National Library – over 600,000 volumes, 750 workstations and 200+ computers across 7 floors.',
          link: 'https://knjiznica.ffzg.unizg.hr/' } },

  { id: 'info-centar', cat: 'zivot',
    hr: { title: 'Izgubljen/a? Info-centar je odmah pored ulaza',
          body: 'Odmah desno od glavnog ulaza – rade ga studenti viših godina koji znaju faks u dušu. Pitaj ih gdje je koja dvorana, kome se javiti za što, i mogu ti izdati iksicu.',
          link: 'https://infocentar.ffzg.unizg.hr/' },
    en: { title: 'Lost? Info centre is right by the entrance',
          body: 'Just right of the main entrance – staffed by upper-year students who know the faculty inside out. Ask them where any room is, who to talk to, and they can issue your student ID (iksica) too.',
          link: 'https://infocentar.ffzg.unizg.hr/' } },

  { id: 'udruge', cat: 'zivot',
    hr: { title: 'Preko 20 studentskih udruga i klubova',
          body: 'Od KSFF-a do odsjeknih klubova (povjesničari, kroatisti, sociolozi...). Najbrži prečac za upoznavanje, projekte i praksu.',
          link: 'https://web2020.ffzg.unizg.hr/studenti/studentske-udruge-i-klubovi/' },
    en: { title: 'Over 20 student clubs and associations',
          body: 'From KSFF to department clubs (historians, Croatists, sociologists...). The fastest shortcut for meeting people, projects and practical experience.',
          link: 'https://web2020.ffzg.unizg.hr/studenti/studentske-udruge-i-klubovi/' } },

  { id: 'iksica-kultura', cat: 'zivot',
    hr: { title: 'Iksica = zlatna karta za kulturu',
          body: 'HNK Zagreb, Gavella, MSU i brojna kina nude studentske popuste. Teatar &TD u sklopu SC-a nudi posebno povoljne ulaznice. Uvijek pitaj na blagajni.',
          link: 'https://www.sczg.unizg.hr/kultura' },
    en: { title: 'Student ID = golden ticket for culture',
          body: 'HNK Zagreb, Gavella, MSU and many cinemas offer student discounts. The &TD Theatre in the SC complex has especially good deals. Always ask at the box office.',
          link: 'https://www.sczg.unizg.hr/kultura' } },

{ id: 'aai', cat: 'sustavi',
    hr: { title: 'AAI@EduHr – jedan račun za sve',
          body: 'Korisničko ime s upisa (korisnik@ffzg.hr) otvara Omegu, Studomat/ISVU, besplatni Eduroam Wi-Fi i Microsoft 365 s 1 TB OneDrive prostora. Aktiviraj odmah.',
          link: 'https://www.eduroam.hr/' },
    en: { title: 'AAI@EduHr – one account for everything',
          body: 'Your enrolment username (user@ffzg.hr) unlocks Omega, Studomat/ISVU, free Eduroam Wi-Fi and Microsoft 365 with 1 TB OneDrive storage. Activate it immediately.',
          link: 'https://www.eduroam.hr/' } },

  { id: 'aai-lozinka', cat: 'sustavi',
    hr: { title: 'Spremi AAI lozinku na sigurno mjesto – odmah',
          body: 'Bez AAI@EduHr nemaš pristup ničemu. Obnavljanje lozinke može potrajati i nekoliko dana – nemoj čekati da je izgubiš.',
          link: null },
    en: { title: 'Save your AAI password somewhere safe – now',
          body: 'Without AAI@EduHr you have no access to anything. Recovering a lost password can take several days – don\'t wait until it\'s gone.',
          link: null } },

  { id: 'omega', cat: 'sustavi',
    hr: { title: 'Omega – prati od prvog dana',
          body: 'Moodle platforma FFZG-a. Profesori tu objavljuju svu literaturu, prezentacije i rokove. Neke obavijesti ne dolaze nigdje drugdje. Lozinku za pristup kolegiju dobivaš na prvom predavanju.',
          link: 'https://omega.ffzg.hr/' },
    en: { title: 'Omega – follow it from day one',
          body: 'FFZG\'s Moodle platform. Professors post all literature, slides and deadlines here. Some announcements exist nowhere else. You get the course password at the first lecture.',
          link: 'https://omega.ffzg.hr/' } },

  { id: 'office365', cat: 'sustavi',
    hr: { title: 'Besplatni Microsoft 365 za studente',
          body: 'Kroz AAI@EduHr identitet imaš besplatnu licencu za cijeli Office paket (Word, Excel, PowerPoint...) i 1 TB OneDrive pohrane.',
          link: 'https://office365.skole.hr/' },
    en: { title: 'Free Microsoft 365 for students',
          body: 'Your AAI@EduHr identity gives you a free licence for the entire Office suite (Word, Excel, PowerPoint...) and 1 TB OneDrive storage.',
          link: 'https://office365.skole.hr/' } },

  { id: 'studomat-rok', cat: 'sustavi',
    hr: { title: 'Studomat zatvori prijavu ispita 48h ranije',
          body: 'Ne čekaj zadnji trenutak – sustav zna biti spor ili pasti pred rokove. Prijavi ispit čim znaš da ideš.',
          link: 'https://isvu.hr/studomat' },
    en: { title: 'Studomat closes exam registration 48h early',
          body: 'Don\'t wait until the last moment – the system can be slow or crash before deadlines. Register as soon as you know you\'re going.',
          link: 'https://isvu.hr/studomat' } },

  { id: 'potpis', cat: 'studij',
    hr: { title: 'Provjeri uvjete za potpis od prvog tjedna',
          body: 'Puno kolegija boduje ili uvjetuje prisutnost. Od prvog tjedna provjeri uvjete za potpis za svaki predmet – bez potpisa nema upisa više godine.',
          link: null },
    en: { title: 'Check attendance requirements from week one',
          body: 'Many courses grade or require attendance. From week one, check the signature conditions for every subject – without the signature you can\'t enrol in the next year.',
          link: null } },

{ id: 'tzk', cat: 'studij',
    hr: { title: 'TZK je obavezan – ne ignoriraj ga',
          body: 'Tjelesna i zdravstvena kultura obavezna je na prvoj i drugoj godini preddiplomskog studija. Bez dovoljno dolazaka nema potpisa. Biraš između Sljemena, streličarstva, joge, plesa, borilačkih vještina i još mnogo toga.',
          link: 'https://tzk.ffzg.unizg.hr/' },
    en: { title: 'PE is mandatory – don\'t ignore it',
          body: 'Physical education is compulsory in the first and second year of undergraduate study. Not enough attendance means no signature. Choose from Sljeme, archery, yoga, dance, martial arts and more.',
          link: 'https://tzk.ffzg.unizg.hr/' } },

  { id: 'sistematski', cat: 'pomoc',
    hr: { title: 'Obavezan sistematski pregled za brucoše',
          body: 'Svi brucoši moraju obaviti preventivni pregled u studentskoj ambulanti na Sigetu (Avenija Većeslava Holjevca 22). Prati obavijesti na stranici faksa za raspored po odsjecima.',
          link: 'https://www.ffzg.unizg.hr/' },
    en: { title: 'Mandatory health check for first-years',
          body: 'All first-year students must complete a preventive check-up at the student health clinic in Siget (Avenija Većeslava Holjevca 22). Follow faculty notices for your department\'s schedule.',
          link: 'https://www.ffzg.unizg.hr/' } },

{ id: 'menza-svi', cat: 'novac',
    hr: { title: 'Subvencija za prehranu vrijedi i van FFZG-a',
          body: 'Studentska subvencija za prehranu vrijedi na svim sveučilišnim menzama u Zagrebu – ne samo na FFZG-u. Iskoristi menze na FSB-u, Agronomskom, Knežiji i drugima.',
          link: 'https://studentski.hr/' },
    en: { title: 'Meal subsidy works beyond FFZG too',
          body: 'The student meal subsidy is valid at all university canteens in Zagreb, not just FFZG. Use the canteens at FSB, Agronomy faculty, Knežija and others.',
          link: 'https://studentski.hr/' } },

  { id: 'student-servis', cat: 'novac',
    hr: { title: 'Student servis – zarada uz faks',
          body: 'Ugovore i ponudu poslova rješavaš brzo i online. Potvrdu o studiranju za upis u evidenciju besplatno preuzeš putem e-Građana. Usmena preporuka kolega brže funkcionira od online liste.',
          link: 'https://www.sczg.unizg.hr/student-servis/' },
    en: { title: 'Student job agency – earn alongside studying',
          body: 'Manage contracts and job listings quickly online. Download your enrolment certificate via e-Građani for free. A personal recommendation from peers works faster than the online list.',
          link: 'https://www.sczg.unizg.hr/student-servis/' } },

{ id: 'domovi', cat: 'novac',
    hr: { title: 'Studentski domovi – prijave u lipnju',
          body: 'Natječaj se raspisuje svake godine u lipnju. Oni koji ne dobiju dom mogu se prijaviti na subvenciju od 60 € mjesečno za privatni najam. Sava je najveći (4.000+ kreveta, Jarun), Cvjetno ima fitness i restoran.',
          link: 'https://www.sczg.unizg.hr/smjestaj' },
    en: { title: 'Student dorms – applications open in June',
          body: 'Applications open every June. Those who don\'t get a dorm place can apply for a €60/month subsidy for private rent. Sava is the largest (4,000+ beds, Jarun), Cvjetno has a gym and restaurant.',
          link: 'https://www.sczg.unizg.hr/smjestaj' } },

  { id: 'erasmus', cat: 'studij',
    hr: { title: 'Erasmus+ – semestar u inozemstvu uz stipendiju',
          body: 'Erasmus+ nudi financijsku potporu za studij u Španjolskoj, Njemačkoj, Italiji i desecima drugih zemalja EU. Natječaji se raspisuju jednom godišnje – prati Ured za međunarodnu suradnju FFZG-a.',
          link: 'https://www.ffzg.unizg.hr/medunarodna-suradnja/' },
    en: { title: 'Erasmus+ – a semester abroad with a grant',
          body: 'Erasmus+ offers financial support for studying in Spain, Germany, Italy and dozens of other EU countries. Applications open once a year – follow the FFZG International Relations Office.',
          link: 'https://www.ffzg.unizg.hr/medunarodna-suradnja/' } },

{ id: 'mail-profesor', cat: 'studij',
    hr: { title: 'Profesori ne moraju odgovoriti dan prije ispita',
          body: 'Javi se tjedan-dva ranije. Konzultacije se ne koriste dovoljno – većina FFZG profesora je stvarno dostupna i voli konkretan razgovor, a ne samo hrpu mailova pred kraj semestra.',
          link: null },
    en: { title: 'Professors don\'t have to reply the day before the exam',
          body: 'Contact them one or two weeks earlier. Office hours are underused – most FFZG professors are genuinely available and appreciate a focused conversation.',
          link: null } },

  { id: 'skripte', cat: 'studij',
    hr: { title: 'Pitaj starije kolege za provjerene skripte',
          body: 'Službena literatura je često preopširna. Iskusni studenti već znaju što profesor stvarno pita na ispitu – njihove skripte vrijede zlata.',
          link: null },
    en: { title: 'Ask older students for tried-and-tested notes',
          body: 'Official reading lists are often too broad. Experienced students already know what the professor actually asks in exams – their notes are worth their weight in gold.',
          link: null } },

  { id: 'knjiznica-citalnica', cat: 'zivot',
    hr: { title: 'Tiha čitaonica – dođi rano u ispitnim rokovima',
          body: 'Čitaonica na višim katovima knjižnice je zlato za učenje – ali mjesta nestaju brzo. Tiskanje u knjižnici košta sitniš.',
          link: 'https://knjiznica.ffzg.unizg.hr/' },
    en: { title: 'Silent reading room – arrive early during exam season',
          body: 'The reading room on the upper floors of the library is perfect for studying – but spots fill fast. Printing in the library costs next to nothing.',
          link: 'https://knjiznica.ffzg.unizg.hr/' } },

  { id: 'knjige-knjiznica', cat: 'novac',
    hr: { title: 'Ne kupuj odmah sve knjige s popisa',
          body: 'Knjige iz knjižnice možeš zadužiti na dulji period. Puno toga s popisa literature ćeš preskočiti – pričekaj da vidiš što profesor stvarno zadaje.',
          link: 'https://knjiznica.ffzg.unizg.hr/' },
    en: { title: 'Don\'t buy every book on the reading list right away',
          body: 'Library books can be borrowed for extended periods. You\'ll skip a lot of what\'s on the list – wait and see what the professor actually assigns.',
          link: 'https://knjiznica.ffzg.unizg.hr/' } },

  { id: 'zbor-drustvene-mreze', cat: 'zivot',
    hr: { title: 'Prati Studentski zbor i odsjek na društvenim mrežama',
          body: 'Brze obavijesti, natječaji, eventi i važni rokovi najbrže dolaze preko profila Studentskog zbora FFZG-a i tvog odsjeka – ne čekaj newsletter.',
          link: 'https://szbor.ffzg.unizg.hr/' },
    en: { title: 'Follow the Student Council and department on social media',
          body: 'Quick updates, competitions, events and important deadlines arrive fastest via the FFZG Student Council and your department\'s profiles – don\'t wait for the newsletter.',
          link: 'https://szbor.ffzg.unizg.hr/' } },

  { id: 'theta', cat: 'sustavi',
    hr: { title: 'Theta – što moraš položiti i koliko ECTS-a',
          body: 'Na Theti pronađeš ECTS informacijski paket svog studija – popis svih obveznih i izbornih kolegija, broj bodova, literaturu i preduvjete za upis viših godina. Odaberi "Novi i reformirani studiji" pa pronađi svoj odsjek. Pristup je slobodan, bez prijave.',
          link: 'https://thetha.ffzg.hr/ECTS/' },
    en: { title: 'Theta – what you need to pass and how many ECTS',
          body: 'Theta has the ECTS information package for your programme – all mandatory and elective courses, credit values, reading lists and prerequisites for higher years. Select "Novi i reformirani studiji", then find your department. No login required.',
          link: 'https://thetha.ffzg.hr/ECTS/' } },

  { id: 'e-molba', cat: 'studij',
    hr: { title: 'E-molba – digitalni zahtjev koji mora stići na vrijeme',
          body: 'Sve službene zahtjeve (naknadni upis/ispis kolegija, više od 35 ECTS-a, mirovanje...) šalješ kroz portal za e-molbe. Sustav automatski odbija zakasnele molbe – provjeri rokove u akademskom kalendaru prije nego što klikneš Pošalji. Odgovor stiže na @m.ffzg.hr mail.',
          link: 'https://molbe.ffzg.hr/' },
    en: { title: 'E-molba – digital requests that must arrive on time',
          body: 'All official requests (late course enrolment/drop, exceeding 35 ECTS, study leave...) go through the e-molba portal. The system automatically rejects late submissions – check deadlines in the academic calendar before you click Send. The decision arrives in your @m.ffzg.hr inbox.',
          link: 'https://molbe.ffzg.hr/' } },

  { id: 'ispravi-me', cat: 'studij',
    hr: { title: 'Provjeri svaki seminar na Ispravi.me',
          body: 'Besplatni online servis koji pronalazi pravopisne i gramatičke greške u tekstovima na hrvatskom. Akademsko pisanje na FFZG-u ne tolerira nemar – provuci svaki rad kroz ovaj sustav prije predaje.',
          link: 'https://ispravi.me/' },
    en: { title: 'Run every paper through Ispravi.me',
          body: 'Free online tool that catches spelling and grammar mistakes in Croatian text. Academic writing at FFZG has zero tolerance for sloppiness – run every paper through this before submitting.',
          link: 'https://ispravi.me/' } },

  { id: 'akademska-cetvrt', cat: 'studij',
    hr: { title: 'Akademska četvrt – predavanje počinje 15 minuta nakon',
          body: 'Na faksu predavanje formalno može početi 15 minuta NAKON sata u rasporedu. Profesor to koristi po volji, a isto može vrijediti i za toleranciju kašnjenja studenata. Što to točno znači kod pojedinog profesora – provjeri od starijih kolega.',
          link: null },
    en: { title: 'Academic quarter – the 15-minute rule',
          body: 'A lecture can formally start 15 minutes AFTER the scheduled time. Professors apply this at their discretion, and it can also mean a tolerance window for late-arriving students. What it means in practice depends on the professor – ask older classmates.',
          link: null } },

  { id: 'oznake-dvorana', cat: 'zivot',
    hr: { title: 'Oznake dvorana – A-006 nije tajanstvena šifra',
          body: 'Slovo = trakt (krilo) zgrade. Prva brojka = kat (0 je prizemlje, 1 je prvi kat...). Ostatak = broj dvorane ili kabineta. Dakle A-006 = trakt A, prizemlje, prostorija 6. Trakti su A, B, C, E i F – sve spojeno hodnicima.',
          link: null },
    en: { title: 'Room codes – A-006 isn\'t a secret cipher',
          body: 'Letter = building wing (trakt). First digit = floor (0 is ground floor, 1 is first floor...). The rest = room number. So A-006 = wing A, ground floor, room 6. Wings are A, B, C, E and F – all connected by corridors.',
          link: null } },

  { id: 'ponistavanje-iksice', cat: 'novac',
    hr: { title: '10. studenog – rok za subvenciju na iksici',
          body: 'Svakog 10. studenog sustav automatski poništava subvenciju za studente koji nisu upisani u tekuću akademsku godinu. Ako ne završiš upis na Studomatu do tog datuma, gubiš pravo na jeftinu hranu u menzi.',
          link: null },
    en: { title: '10 November – student card subsidy deadline',
          body: 'Every 10 November the system automatically cancels the meal subsidy for students not enrolled in the current academic year. If you haven\'t completed enrolment on Studomat by that date, you lose discounted canteen meals.',
          link: null } },

  { id: 'kolokvij', cat: 'studij',
    hr: { title: 'Kolokvij – može biti zamjena za ispit',
          body: 'Kolokvij je parcijalna provjera znanja koja može biti preduvjet za ispit, zamijeniti dio gradiva ili potpuno zamijeniti završni ispit. Što kolokvij znači na konkretnom kolegiju uvijek piše u izvedbenom planu – ili pitaš profesora na prvom predavanju.',
          link: null },
    en: { title: 'Kolokvij – can replace the final exam',
          body: 'A kolokvij is a partial test that can be a prerequisite for the exam, replace part of the exam material, or replace the final exam entirely. What it means on a specific course is in the course outline – or ask the professor at the first lecture.',
          link: null } },

  { id: 'prilagodba', cat: 'pomoc',
    hr: { title: 'Prilagodba – podrška studentima s invaliditetom ili kroničnim bolestima',
          body: 'Ured za akademsku prilagodbu organizira prilagodbu nastave, kolokvija i ispita za studente s invaliditetom, oštećenjima vida/sluha, disleksijom, ADHD-om ili kroničnim bolestima. Kontaktiraj ih mailom na prilagodba@m.ffzg.hr.',
          link: 'https://prilagodba.ffzg.unizg.hr/' },
    en: { title: 'Prilagodba – support for students with disabilities or chronic conditions',
          body: 'The Academic Accommodation Office arranges adjustments to classes, colloquiums and exams for students with disabilities, vision/hearing impairments, dyslexia, ADHD or chronic conditions. Email prilagodba@m.ffzg.hr.',
          link: 'https://prilagodba.ffzg.unizg.hr/' } },

  { id: 'tajnistvo', cat: 'studij',
    hr: { title: 'Tajništvo odsjeka – nije ista stvar kao referada',
          body: 'Svaki odsjek ima vlastito tajništvo na svom katu. Tamo predaješ papire specifične za smjer, rješavaš upis u seminarske grupe i preuzimaš potvrde vezane za tvoj studij. Za probleme koje centralna referada ne može riješiti – idi do tajnice svog odsjeka.',
          link: 'https://web2020.ffzg.unizg.hr/ustroj/odsjeci/' },
    en: { title: 'Department secretariat – not the same as the referada',
          body: 'Every department has its own secretariat on its floor. That\'s where you submit department-specific paperwork, sort seminar group enrolment and collect programme certificates. For problems the central referada can\'t solve – go to your department secretary.',
          link: 'https://web2020.ffzg.unizg.hr/ustroj/odsjeci/' } },

  { id: 'it-podrska', cat: 'sustavi',
    hr: { title: 'IT podrška – za AAI, Omegu i Wi-Fi probleme',
          body: 'Za probleme s prijavom na Omegu ili Studomat, reset AAI lozinke ili spajanje na Eduroam Wi-Fi – piši na podrska@ffzg.hr. Za probleme s elektroničkim identitetom (AAI) piši na aai@ffzg.hr.',
          link: 'https://web2020.ffzg.unizg.hr/it-sluzba/' },
    en: { title: 'IT support – for AAI, Omega and Wi-Fi issues',
          body: 'For login problems with Omega or Studomat, AAI password resets or connecting to Eduroam Wi-Fi – email podrska@ffzg.hr. For issues specifically with your electronic identity (AAI) email aai@ffzg.hr.',
          link: 'https://web2020.ffzg.unizg.hr/it-sluzba/' } },
];

/* category metadata */
window.KOMPAS_CATS = {
  studij:  { hr: 'Studij',   en: 'Studies',  color: 'var(--cat-studij)',  icon: 'ti-school' },
  sustavi: { hr: 'Sustavi',  en: 'Systems',  color: 'var(--cat-sustavi)', icon: 'ti-sitemap' },
  novac:   { hr: 'Novac',    en: 'Money',    color: 'var(--cat-novac)',   icon: 'ti-coin' },
  zivot:   { hr: 'Život',    en: 'Life',     color: 'var(--cat-zivot)',   icon: 'ti-mug' },
  pomoc:   { hr: 'Pomoć',    en: 'Help',     color: 'var(--cat-pomoc)',   icon: 'ti-shield-check' },
};

/* ── room category metadata ── */
window.KOMPAS_ROOM_CATS = {
  ucionica: { hr: 'Učionica',     en: 'Classroom',  color: '#83a598', icon: 'ti-chalkboard' },
  odsjek:   { hr: 'Odsjek',       en: 'Department', color: '#d3869b', icon: 'ti-building-community' },
  wc:       { hr: 'WC',           en: 'Restrooms',  color: '#928374', icon: 'ti-building' },
  usluge:   { hr: 'Usluge',       en: 'Services',   color: '#fabd2f', icon: 'ti-tools' },
  sluzbe:   { hr: 'Uredi / Službe', en: 'Offices',  color: '#fb4934', icon: 'ti-briefcase' },
};

/* ── building rooms ──
   ids match the element ids inside each maps/floor-N.svg #rooms layer.
   floor: '0' = prizemlje. cat drives the sidebar badge; map colour is by tract. */
window.KOMPAS_ROOMS = [

  /* ── PRIZEMLJE (floor 0) ── */
  { id: '0-A001', floor: '0', cat: 'ucionica',
    hr: { name: 'A-001', desc: 'Učionica u prizemlju.', link: null },
    en: { name: 'A-001', desc: 'Ground-floor classroom.', link: null } },
  { id: '0-A014', floor: '0', cat: 'ucionica',
    hr: { name: 'A-014', desc: 'Učionica u prizemlju.', link: null },
    en: { name: 'A-014', desc: 'Ground-floor classroom.', link: null } },
  { id: '0-A018', floor: '0', cat: 'ucionica',
    hr: { name: 'A-018', desc: 'Učionica u prizemlju.', link: null },
    en: { name: 'A-018', desc: 'Ground-floor classroom.', link: null } },

  { id: '0-B', floor: '0', cat: 'odsjek',
    aliases: ['B001','B002','B003','B004','B005','B006','B007','B008','B009','B010','B011','B012','B013','B014','B015','B016','B017','B018','B019','B020','B021','B022','B023','B024','B025','B026'],
    hr: { name: 'B-trakt', desc: 'B-001 – B-026. Između podruma i prizemlja. Anglistika, Lingvistika, Orijentalistika i Hungarologija.', link: null },
    en: { name: 'B-wing', desc: 'B-001 – B-026. Between basement and ground floor. English Studies, Linguistics, Oriental and Hungarian Studies.', link: null } },
  { id: '0-anglistika', floor: '0', cat: 'odsjek', tractId: '0-B',
    hr: { name: 'Anglistika', desc: 'B-trakt, između podruma i prizemlja.', link: null },
    en: { name: 'English Studies', desc: 'B-wing, between basement and ground floor.', link: null } },
  { id: '0-lingvistika', floor: '0', cat: 'odsjek', tractId: '0-B',
    hr: { name: 'Lingvistika', desc: 'B-trakt, između podruma i prizemlja.', link: null },
    en: { name: 'Linguistics', desc: 'B-wing, between basement and ground floor.', link: null } },
  { id: '0-orijentalistika', floor: '0', cat: 'odsjek', tractId: '0-B',
    hr: { name: 'Orijentalistika i Hungarologija', desc: 'B-trakt, između podruma i prizemlja.', link: null },
    en: { name: 'Oriental and Hungarian Studies', desc: 'B-wing, between basement and ground floor.', link: null } },
  { id: '0-C', floor: '0', cat: 'odsjek',
    aliases: ['C001','C002','C003','C004','C005','C006','C007','C008','C009','C010','C011','C012','C013','C014','C015','C016','C017','C018','C019','C020','C021','C022','C023','C024','C025','C026'],
    hr: { name: 'C-trakt', desc: 'C-001 – C-026. Između podruma i prizemlja. Arheologija, Etnologija i antropologija.', link: null },
    en: { name: 'C-wing', desc: 'C-001 – C-026. Between basement and ground floor. Archaeology, Ethnology and Anthropology.', link: null } },
  { id: '0-arheologija', floor: '0', cat: 'odsjek', tractId: '0-C',
    hr: { name: 'Arheologija', desc: 'C-trakt, između podruma i prizemlja.', link: null },
    en: { name: 'Archaeology', desc: 'C-wing, between basement and ground floor.', link: null } },
  { id: '0-etnologija', floor: '0', cat: 'odsjek', tractId: '0-C',
    hr: { name: 'Etnologija i antropologija', desc: 'C-trakt, između podruma i prizemlja.', link: null },
    en: { name: 'Ethnology and Anthropology', desc: 'C-wing, between basement and ground floor.', link: null } },

  { id: '0-D1', floor: '0', cat: 'ucionica',
    hr: { name: 'D-1', desc: 'Velika predavaonica u prizemlju.', link: null },
    en: { name: 'D-1', desc: 'Large lecture hall on the ground floor.', link: null } },
  { id: '0-D2', floor: '0', cat: 'ucionica',
    hr: { name: 'D-2', desc: 'Velika predavaonica u prizemlju.', link: null },
    en: { name: 'D-2', desc: 'Large lecture hall on the ground floor.', link: null } },
  { id: '0-D3', floor: '0', cat: 'ucionica',
    hr: { name: 'D-3', desc: 'Velika predavaonica u prizemlju.', link: null },
    en: { name: 'D-3', desc: 'Large lecture hall on the ground floor.', link: null } },
  { id: '0-D4', floor: '0', cat: 'ucionica',
    hr: { name: 'D-4', desc: 'Velika predavaonica u prizemlju.', link: null },
    en: { name: 'D-4', desc: 'Large lecture hall on the ground floor.', link: null } },
  { id: '0-D5', floor: '0', cat: 'ucionica',
    hr: { name: 'D-5', desc: 'Velika predavaonica u prizemlju.', link: null },
    en: { name: 'D-5', desc: 'Large lecture hall on the ground floor.', link: null } },
  { id: '0-D6', floor: '0', cat: 'ucionica',
    hr: { name: 'D-6', desc: 'Velika predavaonica u prizemlju.', link: null },
    en: { name: 'D-6', desc: 'Large lecture hall on the ground floor.', link: null } },
  { id: '0-D7', floor: '0', cat: 'ucionica',
    hr: { name: 'D-7', desc: 'Najveća dvorana na faksu. Koristi se za skupove, tribine i plenume.', link: null },
    en: { name: 'D-7', desc: 'The largest hall in the building. Used for assemblies, public debates and plenary sessions.', link: null } },
  { id: '0-D01', floor: '0', cat: 'sluzbe',
    hr: { name: 'Uredi', desc: 'D01 – D08. Uredi u prizemlju.', link: null },
    en: { name: 'Offices', desc: 'D01 – D08. Ground-floor offices.', link: null } },
  { id: '0-D01-1', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D01', desc: 'Ured u prizemlju.' },
    en: { name: 'D01', desc: 'Ground-floor office.' } },
  { id: '0-D01-2', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D02', desc: 'Ured u prizemlju.' },
    en: { name: 'D02', desc: 'Ground-floor office.' } },
  { id: '0-D01-3', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D03', desc: 'Ured u prizemlju.' },
    en: { name: 'D03', desc: 'Ground-floor office.' } },
  { id: '0-D01-4', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D04', desc: 'Ured u prizemlju.' },
    en: { name: 'D04', desc: 'Ground-floor office.' } },
  { id: '0-D01-5', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D05', desc: 'Ured u prizemlju.' },
    en: { name: 'D05', desc: 'Ground-floor office.' } },
  { id: '0-D01-6', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D06', desc: 'Ured u prizemlju.' },
    en: { name: 'D06', desc: 'Ground-floor office.' } },
  { id: '0-D01-7', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D07', desc: 'Ured u prizemlju.' },
    en: { name: 'D07', desc: 'Ground-floor office.' } },
  { id: '0-D01-8', floor: '0', cat: 'sluzbe', tractId: '0-D01',
    hr: { name: 'D08', desc: 'Ured u prizemlju.' },
    en: { name: 'D08', desc: 'Ground-floor office.' } },

  { id: '0-porta', floor: '0', cat: 'sluzbe',
    hr: { name: 'Porta', desc: 'Recepcija na glavnom ulazu. Tu su i pošta i izgubljeno-nađeno.', link: null },
    en: { name: 'Porter / reception', desc: 'Reception at the main entrance. Mail and lost-and-found here.', link: null } },
  { id: '0-infocentar', floor: '0', cat: 'usluge',
    hr: { name: 'Info centar', desc: 'Opće informacije za studente i posjetitelje. Radno vrijeme: 9-14h ', link: null },
    en: { name: 'Info centre', desc: 'General information for students and visitors. Working hours: 9-14', link: null } },
  { id: '0-knjiznica', floor: '0', cat: 'usluge',
    hr: { name: 'Knjižnica', desc: 'Glavna knjižnica FFZG-a. Posuđuješ s iksicom. Radi pon–pet 7:30–20, sub 9–14.', link: 'https://knjiznica.ffzg.unizg.hr/' },
    en: { name: 'Library', desc: 'Main FFZG library. Borrow with your student card. Mon–Fri 8–30, Sat 9–14.', link: 'https://knjiznica.ffzg.unizg.hr/' } },
  { id: '0-knjizara', floor: '0', cat: 'usluge',
    hr: { name: 'Knjižara', desc: 'Prodaja udžbenika, skripti i pribora.', link: null },
    en: { name: 'Bookstore', desc: 'Textbooks, course readers and supplies.', link: null } },
  { id: '0-fotokopiraona', floor: '0', cat: 'usluge',
    hr: { name: 'Fotokopiraona', desc: 'Kopiranje, tisak i uvez po studentskim cijenama.', link: null },
    en: { name: 'Copy shop', desc: 'Copying, printing and binding at student prices.', link: null } },
  { id: '0-menza', floor: '0', cat: 'usluge',
    hr: { name: 'Menza', desc: 'Studentska menza. Radi 11–15h.', link: 'https://www.sczg.unizg.hr/prehrana/restorani/filozofski-fakultet' },
    en: { name: 'Canteen', desc: 'Student canteen. Open 11–15.', link: 'https://www.sczg.unizg.hr/prehrana/restorani/filozofski-fakultet' } },
  { id: '0-KSFF', floor: '0', cat: 'usluge',
    hr: { name: 'KSFF', desc: 'Klub studenata Filozofskog fakulteta – kafić i okupljalište.', link: null },
    en: { name: 'KSFF', desc: 'Faculty student club – café and hangout spot.', link: null } },
  { id: '0-refreada', floor: '0', cat: 'sluzbe',
    hr: { name: 'Referada', desc: 'Studentska služba – upisi, ispiti, potvrde. Radi pon–pet 10–11, 12-14.', link: null },
    en: { name: 'Registrar', desc: 'Student services – enrolment, exams, certificates. Mon–Fri 10–11, 12-14.', link: null } },
  { id: '0-dekanat', floor: '0', cat: 'sluzbe',
    hr: { name: 'Dekanat', desc: 'Uprava fakulteta.', link: null },
    en: { name: "Dean's office", desc: 'Faculty administration.', link: null } },
  { id: '0-savjetovaliste', floor: '0', cat: 'sluzbe',
    hr: { name: 'Savjetovalište', desc: 'Besplatno psihološko savjetovanje za studente.', link: 'https://savjetovaliste.ffzg.unizg.hr/' },
    en: { name: 'Counselling', desc: 'Free psychological counselling for students.', link: 'https://savjetovaliste.ffzg.unizg.hr/' } },
  { id: '0-prilagodba', floor: '0', cat: 'sluzbe',
    hr: { name: 'Ured za prilagodbu studija', desc: 'Podrška studentima s invaliditetom i prilagodba studijskih obveza.', link: null },
    en: { name: 'Accessibility office', desc: 'Support for students with disabilities and study accommodations.', link: null } },

  { id: '0-lift', floor: '0', cat: 'usluge',
    group: ['0-elevator-1','0-elevator-2','0-elevator-3'],
    hr: { name: 'Lift (Prizemlje)', desc: 'Dizala u prizemlju.', link: null },
    en: { name: 'Lift (Ground floor)', desc: 'Ground-floor elevators.', link: null } },
  { id: '0-wc', floor: '0', cat: 'wc',
    group: ['0-toilet-1','0-toilet-2'],
    hr: { name: 'WC (Prizemlje)', desc: 'Toaleti u prizemlju.', link: null },
    en: { name: 'WC (Ground floor)', desc: 'Ground-floor restrooms.', link: null } },

  /* ── 1. KAT ── */
  { id: '1-A-1', floor: '1', cat: 'ucionica',
    aliases: ['A101','A102','A103','A104','A105','A106','A107','A108','A109','A110','A111'],
    hr: { name: 'A-101 – A-111', desc: 'Niz učionica A-101 do A-111.', link: null },
    en: { name: 'A-101 – A-111', desc: 'Classrooms A-101 through A-111.', link: null } },
  { id: '1-A-2', floor: '1', cat: 'ucionica',
    aliases: ['A112','A113','A114','A115','A116','A117','A118','A119'],
    hr: { name: 'A-112 – A-119', desc: 'Niz učionica A-112 do A-119.', link: null },
    en: { name: 'A-112 – A-119', desc: 'Classrooms A-112 through A-119.', link: null } },
  { id: '1-A-3', floor: '1', cat: 'ucionica',
    aliases: ['A120','A121','A122','A123','A124','A125','A126','A127','A128','A129','A129a'],
    hr: { name: 'A-120 – A-129a', desc: 'Niz učionica A-120 do A-129a.', link: null },
    en: { name: 'A-120 – A-129a', desc: 'Classrooms A-120 through A-129a.', link: null } },
  { id: '1-B', floor: '1', cat: 'odsjek',
    aliases: ['B101','B102','B103','B104','B105','B106','B107','B108','B109','B110','B111','B112','B113','B114','B115','B116','B117','B118','B119','B120','B121','B122','B123','B124','B125','B126','B127'],
    hr: { name: 'B-trakt', desc: 'B-101 – B-127. Između prizemlja i 1. kata. Kroatistika.', link: null },
    en: { name: 'B-wing', desc: 'B-101 – B-127. Between ground floor and 1st floor. Croatian Studies.', link: null } },
  { id: '1-kroatistika', floor: '1', cat: 'odsjek', tractId: '1-B',
    hr: { name: 'Kroatistika', desc: 'B-trakt, između prizemlja i 1. kata.', link: null },
    en: { name: 'Croatian Studies', desc: 'B-wing, between ground floor and 1st floor.', link: null } },
  { id: '1-C', floor: '1', cat: 'odsjek',
    aliases: ['C101','C102','C103','C104','C105','C106','C107','C108','C109','C110','C111','C112','C113','C114','C115','C116','C117','C118','C119','C120','C121','C122','C123','C124','C125','C126'],
    hr: { name: 'C-trakt', desc: 'C-101 – C-126. Između prizemlja i 1. kata. Povijest i povijest umjetnosti.', link: null },
    en: { name: 'C-wing', desc: 'C-101 – C-126. Between ground floor and 1st floor. History and Art History.', link: null } },
  { id: '1-povijest', floor: '1', cat: 'odsjek', tractId: '1-C',
    hr: { name: 'Povijest', desc: 'C-trakt, između prizemlja i 1. kata.', link: null },
    en: { name: 'History', desc: 'C-wing, between ground floor and 1st floor.', link: null } },
  { id: '1-povijest-umjetnosti', floor: '1', cat: 'odsjek', tractId: '1-C',
    hr: { name: 'Povijest umjetnosti', desc: 'C-trakt, između prizemlja i 1. kata.', link: null },
    en: { name: 'Art History', desc: 'C-wing, between ground floor and 1st floor.', link: null } },
  { id: '1-Croaticum', floor: '1', cat: 'usluge',
    hr: { name: 'Croaticum', desc: 'Centar za hrvatski kao strani jezik. Tečajevi za strance i studente na razmjeni.', link: 'https://croaticum.ffzg.unizg.hr/' },
    en: { name: 'Croaticum', desc: 'Centre for Croatian as a foreign language. Courses for international and exchange students.', link: 'https://croaticum.ffzg.unizg.hr/' } },
  { id: '1-lift', floor: '1', cat: 'usluge',
    group: ['1-elevator-1','1-elevator-2','1-elevator-3'],
    hr: { name: 'Lift (1. kat)', desc: 'Dizala na 1. katu.', link: null },
    en: { name: 'Lift (1st floor)', desc: 'First-floor elevators.', link: null } },
  { id: '1-wc', floor: '1', cat: 'wc',
    group: ['1-toilet'],
    hr: { name: 'WC (1. kat)', desc: 'Toaleti na 1. katu.', link: null },
    en: { name: 'WC (1st floor)', desc: 'First-floor restrooms.', link: null } },

  /* ── 2. KAT ── */
  { id: '2-A-1', floor: '2', cat: 'ucionica',
    aliases: ['A201','A202','A203','A204','A205','A206','A207','A208','A209','A210','A211'],
    hr: { name: 'A-201 – A-211', desc: 'Niz učionica u traktu A.', link: null },
    en: { name: 'A-201 – A-211', desc: 'Run of A-wing classrooms.', link: null } },
  { id: '2-A-2', floor: '2', cat: 'ucionica',
    aliases: ['A212','A213','A214','A215','A216','A217','A218','A219'],
    hr: { name: 'A-212 – A-219', desc: 'Niz učionica u traktu A.', link: null },
    en: { name: 'A-212 – A-219', desc: 'Run of A-wing classrooms.', link: null } },
  { id: '2-A-3', floor: '2', cat: 'ucionica',
    aliases: ['A220','A221','A222','A223','A224','A225','A226','A227','A228','A229'],
    hr: { name: 'A-220 – A-229', desc: 'Niz učionica u traktu A.', link: null },
    en: { name: 'A-220 – A-229', desc: 'Run of A-wing classrooms.', link: null } },
  { id: '2-B', floor: '2', cat: 'odsjek',
    aliases: ['B201','B202','B203','B204','B205','B206','B207','B208','B209','B210','B211','B212','B213','B214','B215','B216','B217','B218','B219','B220','B221','B222','B223','B224','B225','B226'],
    hr: { name: 'B-trakt', desc: 'B-201 – B-226. Između 1. i 2. kata. Slavistika, Komparativna književnost.', link: null },
    en: { name: 'B-wing', desc: 'B-201 – B-226. Between 1st and 2nd floor. Slavic Studies, Comparative Literature.', link: null } },
  { id: '2-slavistika', floor: '2', cat: 'odsjek', tractId: '2-B',
    hr: { name: 'Slavistika', desc: 'B-trakt, između 1. i 2. kata.', link: null },
    en: { name: 'Slavic Studies', desc: 'B-wing, between 1st and 2nd floor.', link: null } },
  { id: '2-komparativna', floor: '2', cat: 'odsjek', tractId: '2-B',
    hr: { name: 'Komparativna književnost', desc: 'B-trakt, između 1. i 2. kata.', link: null },
    en: { name: 'Comparative Literature', desc: 'B-wing, between 1st and 2nd floor.', link: null } },
  { id: '2-C', floor: '2', cat: 'odsjek',
    aliases: ['C201','C202','C203','C204','C205','C206','C207','C208','C209','C210','C211','C212','C213','C214','C215','C216','C217','C218','C219','C220','C221','C222','C223','C224','C225','C226','C227'],
    hr: { name: 'C-trakt', desc: 'C-201 – C-227. Između 1. i 2. kata. Filozofija, Pedagogija, Sociologija.', link: null },
    en: { name: 'C-wing', desc: 'C-201 – C-227. Between 1st and 2nd floor. Philosophy, Education, Sociology.', link: null } },
  { id: '2-filozofija', floor: '2', cat: 'odsjek', tractId: '2-C',
    hr: { name: 'Filozofija', desc: 'C-trakt, između 1. i 2. kata.', link: null },
    en: { name: 'Philosophy', desc: 'C-wing, between 1st and 2nd floor.', link: null } },
  { id: '2-pedagogija', floor: '2', cat: 'odsjek', tractId: '2-C',
    hr: { name: 'Pedagogija', desc: 'C-trakt, između 1. i 2. kata.', link: null },
    en: { name: 'Education', desc: 'C-wing, between 1st and 2nd floor.', link: null } },
  { id: '2-sociologija', floor: '2', cat: 'odsjek', tractId: '2-C',
    hr: { name: 'Sociologija', desc: 'C-trakt, između 1. i 2. kata.', link: null },
    en: { name: 'Sociology', desc: 'C-wing, between 1st and 2nd floor.', link: null } },
  { id: '2-lift', floor: '2', cat: 'usluge',
    group: ['2-elevator-1','2-elevator-2','2-elevator-3'],
    hr: { name: 'Lift (2. kat)', desc: 'Dizala na 2. katu.', link: null },
    en: { name: 'Lift (2nd floor)', desc: 'Second-floor elevators.', link: null } },
  { id: '2-wc', floor: '2', cat: 'wc',
    group: ['2-toilet-1','2-toilet-2'],
    hr: { name: 'WC (2. kat)', desc: 'Toaleti na 2. katu.', link: null },
    en: { name: 'WC (2nd floor)', desc: 'Second-floor restrooms.', link: null } },

  /* ── 3. KAT (trakt A se dijeli na krila E (lijevo) i F (desno)) ── */
  { id: '3-A', floor: '3', cat: 'ucionica',
    aliases: ['A301','A302','A303','A304','A305','A306','A307','A308','A309','A310','A311','A312','A313','A314','A315','A316','A317','A318','A319','A320','A321','A322','A323','A324','A325','A326','A327','A328','A329','A330'],
    hr: { name: 'A-301 – A-330', desc: 'Niz učionica A-301 do A-330.', link: null },
    en: { name: 'A-301 – A-330', desc: 'Classrooms A-301 through A-330.', link: null } },
  { id: '3-E', floor: '3', cat: 'ucionica',
    aliases: ['E301','E302','E303','E304','E305','E306','E307','E308','E309','E310','E311','E312','E313','E314','E315','E316','E317','E318','E319','E320','E321','E322','E323','E324','E325','E326','E327','E328','E329','E330'],
    hr: { name: 'E-trakt', desc: 'E-301 – E-330. Germanistika, Informacijske znanosti.', link: null },
    en: { name: 'E-wing', desc: 'E-301 – E-330. German Studies, Information Sciences.', link: null } },
  { id: '3-germanistika', floor: '3', cat: 'odsjek', tractId: '3-E',
    hr: { name: 'Germanistika', desc: 'E-trakt, 3. kat.', link: null },
    en: { name: 'German Studies', desc: 'E-wing, 3rd floor.', link: null } },
  { id: '3-informacijske', floor: '3', cat: 'odsjek', tractId: '3-E',
    hr: { name: 'Informacijske znanosti', desc: 'E-trakt, 3. kat.', link: null },
    en: { name: 'Information Sciences', desc: 'E-wing, 3rd floor.', link: null } },
  { id: '3-F', floor: '3', cat: 'ucionica',
    aliases: ['F301','F302','F303','F304','F305','F306','F307','F308','F309','F310','F311','F312','F313','F314','F315','F316','F317','F318','F319','F320','F321','F322','F323','F324','F325','F326','F327','F328','F329','F330'],
    hr: { name: 'F-trakt', desc: 'F-301 – F-330. Romanistika, Talijanistika, Klasična filologija.', link: null },
    en: { name: 'F-wing', desc: 'F-301 – F-330. Romance Studies, Italian Studies, Classical Philology.', link: null } },
  { id: '3-romanistika', floor: '3', cat: 'odsjek', tractId: '3-F',
    hr: { name: 'Romanistika', desc: 'F-trakt, 3. kat.', link: null },
    en: { name: 'Romance Studies', desc: 'F-wing, 3rd floor.', link: null } },
  { id: '3-talijanistika', floor: '3', cat: 'odsjek', tractId: '3-F',
    hr: { name: 'Talijanistika', desc: 'F-trakt, 3. kat.', link: null },
    en: { name: 'Italian Studies', desc: 'F-wing, 3rd floor.', link: null } },
  { id: '3-klasicna-filologija', floor: '3', cat: 'odsjek', tractId: '3-F',
    hr: { name: 'Klasična filologija', desc: 'F-trakt, 3. kat.', link: null },
    en: { name: 'Classical Philology', desc: 'F-wing, 3rd floor.', link: null } },
  { id: '3-B', floor: '3', cat: 'odsjek',
    aliases: ['B301','B302','B303','B304','B305','B306','B307','B308','B309','B310','B311','B312','B313','B314','B315','B316','B317','B318','B319','B320','B321','B322','B323','B324','B325','B326'],
    hr: { name: 'B-trakt', desc: 'B-301 – B-326. Između 2. i 3. kata. Fonetika, Centar za strane jezike.', link: null },
    en: { name: 'B-wing', desc: 'B-301 – B-326. Between 2nd and 3rd floor. Phonetics, Centre for Foreign Languages.', link: null } },
  { id: '3-fonetika', floor: '3', cat: 'odsjek', tractId: '3-B',
    hr: { name: 'Fonetika', desc: 'B-trakt, između 2. i 3. kata.', link: null },
    en: { name: 'Phonetics', desc: 'B-wing, between 2nd and 3rd floor.', link: null } },
  { id: '3-centar-strani-jezici', floor: '3', cat: 'usluge', tractId: '3-B',
    hr: { name: 'Centar za strane jezike', desc: 'B-trakt, između 2. i 3. kata.', link: null },
    en: { name: 'Centre for Foreign Languages', desc: 'B-wing, between 2nd and 3rd floor.', link: null } },
  { id: '3-C', floor: '3', cat: 'odsjek',
    aliases: ['C301','C302','C303','C304','C305','C306','C307','C308','C309','C310','C311','C312','C313','C314','C315','C316','C317','C318','C319','C320','C321','C322','C323','C324','C325','C326'],
    hr: { name: 'C-trakt', desc: 'C-301 – C-326. Između 2. i 3. kata. Psihologija.', link: null },
    en: { name: 'C-wing', desc: 'C-301 – C-326. Between 2nd and 3rd floor. Psychology.', link: null } },
  { id: '3-psihologija', floor: '3', cat: 'odsjek', tractId: '3-C',
    hr: { name: 'Psihologija', desc: 'C-trakt, između 2. i 3. kata.', link: null },
    en: { name: 'Psychology', desc: 'C-wing, between 2nd and 3rd floor.', link: null } },
  { id: '3-lift', floor: '3', cat: 'usluge',
    group: ['3-elevator-1','3-elevator-2','3-elevator-3'],
    hr: { name: 'Lift (3. kat)', desc: 'Dizala na 3. katu.', link: null },
    en: { name: 'Lift (3rd floor)', desc: 'Third-floor elevators.', link: null } },
  { id: '3-wc', floor: '3', cat: 'wc',
    group: ['3-toilet-1','3-toilet-2'],
    hr: { name: 'WC (3. kat)', desc: 'Toaleti na 3. katu.', link: null },
    en: { name: 'WC (3rd floor)', desc: 'Third-floor restrooms.', link: null } },
];
